export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const CHANGE_DROPDOWN_SELECTION = 'CHANGE_DROPDOWN_SELECTION'

export const CHANGE_CALENDAR_SELECTION = 'CHANGE_CALENDAR_SELECTION'